name:                blog
version:             0.1.0.0
github:              "githubuser/blog"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blog#readme>

dependencies:
- base >= 4.7 && < 5
  # packages
- polysemy-plugin
- polysemy
  # text manipulation
- text
- bytestring
- scrypt
- utf8-string
- aeson
  # network 
- servant
- servant-server
- warp
- network
  # db
- postgresql-simple

library:
  source-dirs: src

executables:
  blog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: 
    - -O2 
    - -flate-specialise 
    - -fspecialise-aggressively
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - blog
    default-extensions:
    - TemplateHaskell
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

tests:
  blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog
